# Generated by Django 4.2.11 on 2025-09-18 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_alter_auctionlistingmodel_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlistingmodel",
            name="bid",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="BidModel",
                to="auctions.bidmodel",
            ),
        ),
        migrations.AlterField(
            model_name="auctionlistingmodel",
            name="comments",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comments",
                to="auctions.commentmodel",
            ),
        ),
    ]
