# Generated by Django 4.2.11 on 2025-08-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_bidmodel_commentmodel_auctionlistingmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlistingmodel",
            name="initial_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
