# Generated by Django 4.2.11 on 2025-08-26 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_auctionlistingmodel_initial_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bidmodel",
            name="initial_price",
        ),
    ]
