# Generated by Django 4.2.11 on 2025-09-18 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_alter_auctionlistingmodel_bid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentmodel",
            name="date_posted",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
