# Generated by Django 4.2.11 on 2025-08-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_remove_bidmodel_initial_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bidmodel",
            name="bid_made",
            field=models.IntegerField(default=0),
        ),
    ]
