# Generated by Django 4.2.11 on 2025-09-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_commentmodel_date_posted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlistingmodel",
            name="initial_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
