# Generated by Django 4.2.11 on 2025-09-23 13:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_alter_auctionlistingmodel_initial_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlistingmodel",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 9, 23, 13, 1, 6, 804219, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.CreateModel(
            name="WatchListModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "auctions_on_watchlist",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auctions_watchlist",
                        to="auctions.auctionlistingmodel",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
