# Generated by Django 4.2.11 on 2025-09-09 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_alter_bidmodel_bid_made"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlistingmodel",
            name="comments",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comments",
                to="auctions.commentmodel",
            ),
        ),
    ]
