# Generated by Django 4.2.11 on 2025-09-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_alter_auctionlistingmodel_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentmodel",
            name="comment_on_auction",
            field=models.TextField(max_length=200, null=True),
        ),
    ]
